### ISSUE TITLE
Socks (v4?) proxy option from PR #63 doesn't work

### ISSUE THREAD

**Issue by RussH** [igniterealtime/Spark#248]
Hi, socks connectivity when selecting the socks proxy doesn't work.
Using: OpenSuse Tumbleweed, x86_64, running ssh with -D option to allow socks forwarding

/usr/share/spark/logs/error.log is empty

when started at a commandline, the error below is given;
Oct 31, 2016 10:18:15 AM org.jivesoftware.spark.util.log.Log error
SEVERE: connection error
java.net.SocketException: Unconnected sockets not implemented
        at javax.net.SocketFactory.createSocket(SocketFactory.java:125)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:573)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:851)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
        at org.jivesoftware.LoginDialog$LoginPanel.lambda$login$1(LoginDialog.java:1070)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedOperationException
        at javax.net.SocketFactory.createSocket(SocketFactory.java:123)
        ... 18 more

Oct 31, 2016 10:18:15 AM org.jivesoftware.spark.util.log.Log warning
WARNING: Exception in Login:
org.jivesoftware.smack.SmackException$NotConnectedException: Client is not, or no longer, connected.
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.throwNotConnectedExceptionIfAppropriate(XMPPTCPConnection.java:343)
        at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:451)
        at org.jivesoftware.LoginDialog$LoginPanel.login(LoginDialog.java:1099)
        at org.jivesoftware.LoginDialog$LoginPanel.access$900(LoginDialog.java:335)
        at org.jivesoftware.LoginDialog$LoginPanel$3.construct(LoginDialog.java:869)
        at org.jivesoftware.spark.util.SwingWorker.lambda$new$1(SwingWorker.java:142)
        at java.lang.Thread.run(Thread.java:745)

**Comment by wrooot** [comment]
I have filed this in our JIRA bug tracker https://issues.igniterealtime.org/browse/SPARK-1826
